FROM jgraph/drawio:24.7.17

COPY docker/drawio/webapp/index.html /usr/local/tomcat/webapps/draw/index.html
COPY docker/drawio/webapp/stencils /usr/local/tomcat/webapps/draw/stencils
COPY docker/drawio/webapp/js/app.min.js /usr/local/tomcat/webapps/draw/js/app.min.js
COPY docker/drawio/webapp/js/croppie/croppie.min.css /usr/local/tomcat/webapps/draw/js/croppie/croppie.min.css
COPY docker/drawio/webapp/js/diagramly/ElectronApp.js /usr/local/tomcat/webapps/draw/js/diagramly/ElectronApp.js
