kind: Deployment
apiVersion: apps/v1
metadata:
  name: dootask-appstore
  labels:
    app: dootask-appstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-appstore
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dootask-appstore
    spec:
     
      containers:
        - name: appstore
          image: 'dootask/appstore:0.1.9'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: RUN_MODE
              value: strict
            - name: HOST_PWD
              value: /tmp
          volumeMounts:
          - name: appstore-data
            mountPath: /var/www/docker/appstore
            subPath: appstore
        - name: re-appstore
          image: rubyroes/fastapi:latest
          ports:
          - containerPort: 8000
          volumeMounts:
            - name: appstore-data
              mountPath: /app/config
              subPath: appstore/config
            - name: appstore-data
              mountPath: /app/apps
              subPath: appstore/apps
            - name: app-py
              mountPath: /app/app.py
              subPath: app.py
      volumes:
        - name: appstore-data
          persistentVolumeClaim:
            claimName: dootask-app-pvc
        - name: app-py
          configMap:
            name: dootask-config
---
apiVersion: v1
kind: Service
metadata:
  name: dootask-appstore
spec:
  ports:
  - port: 80
    name: appstore
    targetPort: 80
  - port: 8000
    name: re
    targetPort: 8000
  selector:
    app: dootask-appstore
