apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-php
  template:
    metadata:
      labels:
        app: dootask-php
    spec:
      initContainers:
      - name: wait-for-job
        image: busybox
        command: ['sh', '-c', 'until [ -f "/app/success" ]; do echo "waiting for init-job to complete"; sleep 2; done']
        volumeMounts:
        - name: app-data
          mountPath: /app
      containers:
      - name: php
        image: kuaifan/php:swoole-8.0.rc21
        env:
        - name: LANG
          value: "C.UTF-8"
        - name: MODE
          value: "production"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_HOST
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_DATABASE
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_PASSWORD
        - name: DB_PREFIX
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: DB_PREFIX
        - name: FLOW_URL
          value: http://dootask-approve
        volumeMounts:
        - name: app-data
          mountPath: /var/www
          subPath: dootask
        - name: app-data
          mountPath: /etc/supervisor/conf.d/
          subPath: supervisor/conf.d/
        - name: app-data
          mountPath: /var/log/supervisor
          subPath: supervisor/log
        - name: app-data
          mountPath: /usr/local/etc/php/php.ini
          subPath: php/php.ini
        - name: env-config
          mountPath: /var/www/.env
          subPath: .env
        - name: tmpfs-volume
          mountPath: /dev/shm 
        - name: app-data
          mountPath: /var/www/docker/appstore
          subPath: appstore
      - name: php-logs
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -F /var/www/storage/logs/*.log 2>/dev/null || true
        volumeMounts:
        - name: app-data
          mountPath: /var/www
          subPath: dootask
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: dootask-app-pvc
      - name: env-config
        configMap:
          name: dootask-config
      - name: tmpfs-volume
        emptyDir:
          sizeLimit: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dootask-php
spec:
  ports:
  - port: 20000
    name: http
  selector:
    app: dootask-php
