apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_ID}.dootask.top
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2048M
    nginx.ingress.kubernetes.io/limit-rate: '5120'
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
spec:
  tls:
    - hosts:
        - ${APP_ID}.dootask.top
      secretName: dootask.top
  rules:
    - host: ${APP_ID}.dootask.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
