apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    upstream service {
        server php:20000 weight=5 max_fails=3 fail_timeout=30s;
        keepalive 16;
    }

    server {
        listen 80;

        root /var/www/public;
        index index.html index.htm index.php;
        client_max_body_size 1024M;
        autoindex off;
        charset utf-8;
        add_header Access-Control-Expose-Headers "Date, Last-Modified, Age" always;

        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        location / {
            try_files $uri @laravels;
        }

        location ~ /\.well-known {
            allow all;
        }

        location = /ws {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600s; # Consider if you really need a 1-hour timeout
            proxy_send_timeout 3600s;
            proxy_connect_timeout 3600s;
            proxy_pass http://service;
        }

        location @laravels {
            proxy_set_header Connection ""; # Important for keepalive with the upstream
            proxy_pass http://service;
        }

        # Appstore location
        location /appstore/ {
            proxy_set_header X-Forwarded-Host $http_x_forwarded_host/appstore; 
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://dootask-appstore.dootask-saas-share.svc/;
        }
        
        location /appstore/api/v1/internal/install {
            proxy_set_header X-Forwarded-Host $http_x_forwarded_host/appstore; 
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://dootask-appstore.dootask-saas-share.svc:8000/;
        }

        location /appstore/api/v1/internal/uninstall {
            proxy_set_header X-Forwarded-Host $http_x_forwarded_host/appstore; 
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://dootask-appstore.dootask-saas-share.svc:8000/;
        }        
        include /var/www/docker/nginx/site/*.conf;
        
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-site-config
data:
  fileview.conf: |
    location /fileview {
        proxy_pass http://dootask-fileview.dootask-saas-share.svc:8012;
    }
  office.conf: |
    location /office/ {
        proxy_set_header X-Forwarded-Host $http_x_forwarded_host/office;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-office.dootask-saas-share.svc/;
    }
    location /office/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://documentserver.dootask-saas-share.svc:8888/;
    }

  drawio.conf: |
    location /drawio/webapp/ {
        proxy_set_header X-Forwarded-Host $http_x_forwarded_host/drawio/webapp;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-drawio.dootask-saas-share.svc:8080/;
    }

    location /drawio/export/ {
        proxy_set_header X-Forwarded-Host $http_x_forwarded_host/drawio/export;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-drawio.dootask-saas-share.svc:8000/;
    }
  minder.conf: |
    location /minder/ {
        proxy_pass http://dootask-minder.dootask-saas-share.svc/;
    }
