apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    upstream service {
        server php:20000 weight=5 max_fails=3 fail_timeout=30s;
        keepalive 16;
    }

    server {
        listen 80;

        root /var/www/public;
        index index.html index.htm index.php;
        client_max_body_size 1024M;
        autoindex off;
        charset utf-8;
        add_header Access-Control-Expose-Headers "Date, Last-Modified, Age" always;

        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        location / {
            try_files $uri @laravels;
        }

        location ~ /\.well-known {
            allow all;
        }

        location = /ws {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600s; # Consider if you really need a 1-hour timeout
            proxy_send_timeout 3600s;
            proxy_connect_timeout 3600s;
            proxy_pass http://service;
        }

        location @laravels {
            proxy_set_header Connection ""; # Important for keepalive with the upstream
            proxy_pass http://service;
        }

        # Appstore location
        location /appstore/ {
            proxy_set_header X-Forwarded-Host $host/appstore; 
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://appstore/;
        }

        include /var/www/docker/nginx/site/*.conf;
        
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-site-config
data:
  fileview.conf: |
    location /fileview {

        proxy_pass http://dootask-fileview:8012;
    }
  office.conf: |
    location /office/ {

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 3600s;
        proxy_pass http://dootask-office/;
    }
  drawio.conf: |
    location /drawio/webapp/ {

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-drawio:8080/;
    }

    location /drawio/export/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-drawio:8000/;
    }
  minder.conf: |
    location /minder/ {

        proxy_pass http://dootask-minder/;
    }
  approve.conf: |
    # 审批
    location /approve/ {
        proxy_pass http://dootask-approve/;
    }
    location /approve/api/ {
        auth_request /approveAuth;
        proxy_pass http://dootask-approve/api/;
    }
    location /approveAuth {
        internal;
        proxy_set_header Content-Type "application/json";
        proxy_set_header Content-Length $request_length;
        proxy_pass http://service/api/approve/verifyToken;
    }
  okr.conf: |
    # OKR
    location /apps/okr/ {
        proxy_pass http://dootask-okr:5566/apps/okr/;
    }
  ai.conf: |
    # AI
    location /ai/ {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_set_header Scheme $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://dootask-ai:5001/;
    }