apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dootask-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 40Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hitosea-rbd-sc
  resources:
    requests:
      storage: 10Gi
