---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dootask-appstore
  namespace: dootask-${APP_ID}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appstore-manager
  namespace: dootask-${APP_ID}
rules:
- apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appstore-manager-binding
  namespace: dootask-${APP_ID}
subjects:
- kind: ServiceAccount
  name: dootask-appstore
  namespace: dootask-${APP_ID}
roleRef:
  kind: Role
  name: appstore-manager
  apiGroup: rbac.authorization.k8s.io
