apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-office
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dootask-office
  template:
    metadata:
      labels:
        app: dootask-office
    spec:

      containers:
      - name: office
        image: thomisus/onlyoffice-documentserver-unlimited:8.3.3
        env:
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_TYPE
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_USER
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: DB_PWD
        - name: AMQP_URI
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: AMQP_URI
        - name: AMQP_TYPE
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: AMQP_TYPE
        - name: REDIS_SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: REDIS_SERVER_HOST
        - name: REDIS_SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: REDIS_SERVER_PORT
        - name: REDIS_SERVER_PASS
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: REDIS_SERVER_PASS
        - name: NGINX_WORKER_PROCESSES
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: NGINX_WORKER_PROCESSES
        - name: JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: office-secret
              key: JWT_ENABLED

        volumeMounts:
        - name: app-data
          mountPath: /var/log/onlyoffice
          subPath: office/logs
        - name: app-data
          mountPath: /var/www/onlyoffice/Data
          subPath: office/data
        
      - name: office-logs
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -F /var/log/onlyoffice/*.log 2>/dev/null || true
        volumeMounts:
        - name: app-data
          mountPath: /var/log/onlyoffice
          subPath: office
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: dootask-office-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: dootask-office
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dootask-office
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dootask-office-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-sc
  resources:
    requests:
      storage: 10Gi