apiVersion: v1
kind: Secret
metadata:
  name: office-secret
type: Opaque
stringData:
  DB_TYPE: "mariadb"
  DB_HOST: "maxscale-repl.hitosea-k8s.svc"
  DB_PORT: "3306"
  DB_NAME: "onlyoffice"
  DB_PWD: "q6KY5lxgMevgpJb"
  DB_USER: "onlyoffice"
  AMQP_URI: "amqp://user:KGNjbPBJtcx3FR7A@rabbitmq:5672/"
  AMQP_TYPE: "rabbitmq"
  REDIS_SERVER_HOST: "hitosea-redis-cluster-headless.hitosea-k8s.svc"
  REDIS_SERVER_PORT: "6379"
  REDIS_SERVER_PASS: ""
  NGINX_WORKER_PROCESSES: "12"
  JWT_ENABLED: "false"
